production:
  adapter: mysql2
  database: rails_premium
  user: root
  host: localhost
  password: root
  socket: '/var/run/mysqld/mysqld.sock'

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
